#pragma once

#ifndef GLOBALDEFINITIONS_HXX
#define GLOBALDEFINITIONS_HXX


#include <QtGlobal>


#define LP_APP_VERSION "0.0.1 rev. 1"
#define LP_QT_VERSION QT_VERSION_STR
#define LP_EIGEN_VERSION "3.2.7"
#define LP_QCUSTOMPLOT_VERSION "1.3.1"
#define LP_BOOST_VERSION "1.60.0"
#define LP_CPPFORMAT_VERSION "1.1.0"
#define LP_CXXPRETTYPRINT_VERSION "master-334db03"
#define LP_ADWAITA_VERSION "3.16.2.1"


#endif // GLOBALDEFINITIONS_HXX
